export const DEV_DEPENDENCIES_APP_REACT_BASE: readonly string[] = [
  '@gmjs/eslint-config',
  '@types/node',
  '@types/react',
  '@types/react-dom',
  '@vitejs/plugin-react',
  'autoprefixer',
  'eslint',
  'postcss',
  'prettier',
  'tailwindcss',
  'ts-node',
  'typescript',
  'vite',
  'vitest',
];

export const DEV_DEPENDENCIES_APP_REACT_STORYBOOK: readonly string[] = [
  '@storybook/addon-essentials',
  '@storybook/addon-interactions',
  '@storybook/addon-links',
  '@storybook/blocks',
  '@storybook/react',
  '@storybook/react-vite',
  '@storybook/testing-library',
  '@storybook/types',
  'storybook',
];

export const DEV_DEPENDENCIES_APP_NEST: readonly string[] = [
  '@gmjs/eslint-config',
  '@jest/globals',
  '@nestjs/cli',
  '@nestjs/schematics',
  '@nestjs/testing',
  '@types/cookie-parser',
  '@types/express',
  '@types/node',
  '@types/supertest',
  'eslint',
  'jest',
  'prettier',
  'shx',
  'source-map-support',
  'supertest',
  'ts-jest',
  'ts-loader',
  'ts-node',
  'tsconfig-paths',
  'type-fest',
  'typescript',
];

export const DEV_DEPENDENCIES_APP_CLI: readonly string[] = [
  '@gmjs/eslint-config',
  '@gmjs/npm-publish-cli',
  '@jest/globals',
  '@types/node',
  'eslint',
  'jest',
  'prettier',
  'shx',
  'ts-jest',
  'ts-node',
  'typescript',
];

export const DEV_DEPENDENCIES_LIB_BROWSER: readonly string[] = [
  '@gmjs/eslint-config',
  '@gmjs/npm-publish-cli',
  '@jest/globals',
  'eslint',
  'jest',
  'prettier',
  'shx',
  'ts-jest',
  'ts-node',
  'typescript',
];

export const DEV_DEPENDENCIES_LIB_NODE: readonly string[] = [
  '@gmjs/eslint-config',
  '@gmjs/npm-publish-cli',
  '@jest/globals',
  '@types/node',
  'eslint',
  'jest',
  'prettier',
  'shx',
  'ts-jest',
  'ts-node',
  'typescript',
];

export const DEV_DEPENDENCIES_LIB_SHARED: readonly string[] = [
  '@gmjs/eslint-config',
  '@gmjs/npm-publish-cli',
  '@jest/globals',
  'eslint',
  'jest',
  'prettier',
  'shx',
  'ts-jest',
  'ts-node',
  'typescript',
];
